# action.yml
name: 'Code Review with ChatGPT'
description: 'Automating code review using ChatGPT with Github Actions integration on PRs for code explanations.'
inputs:
  openai_api_key:  # Openai API Key is typically recovered from a secret
    description: 'OpenAI API Key'
    required: true
    default: ''
  github_token:  # Github token is passed by Github Actions
    description: 'Github API Key'
    required: true
    default: ''
  github_pr_id:  # id of PR to review
    description: 'Github PR ID'
    required: true
    default: ''
  openai_engine:  # The engine to use for the completion.
    description: 'Options are gpt-4, gpt-4 turbo, gpt-3.5-turbo'
    required: false
    default: 'gpt-3.5-turbo'
  openai_temperature:  # id of input
    description: 'What sampling temperature to use. Higher values means the model will take more risks. Try 0.9 for more creative applications, and 0 (argmax sampling) for ones with a well-defined answer.'
    required: false
    default: '0.5'
  openai_max_tokens:  # id of input
    description: 'The maximum number of tokens to generate in the completion.'
    required: false
    default: '2048'
  mode:  # id of input
    description: 'How to capture PR changes. Options: files, patch'
    required: false
    default: 'files'
  included_file_extensions:  # | delimited list of file extensions to include
    description: 'A pipe delimited list of file extensions to include.'
    required: false
    default: ''
  excluded_file_extensions:  # | delimited list of file extensions to exclude
    description: 'A pipe delimited list of file extensions to exclude.'
    required: false
    default: ''
  include_tokens_in_output:  # Whether to include the input tokens in the output when generating sequences
    description: 'Whether to include the input tokens in the output when generating sequences'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.openai_api_key }}
    - ${{ inputs.github_token }}
    - ${{ inputs.github_pr_id }}
    - ${{ inputs.openai_engine }}
    - ${{ inputs.openai_temperature }}
    - ${{ inputs.openai_max_tokens }}
    - ${{ inputs.mode }}
    - ${{ inputs.included_file_extensions }}
    - ${{ inputs.excluded_file_extensions }}
    - ${{ inputs.include_tokens_in_output }}
